### ISSUE TITLE
Formal validation and inverse calculation

### ISSUE THREAD

**Issue by antonioturdo** [DavidePastore/codice-fiscale#11]
Hi. I am writing two classes to make formal validation and inverse calculation. 
If you are interested in merging, I will develop these reusing some of your code and trying to follow your approach, otherwise I am going to make an indipendent repo. 
Let me know.

**Comment by DavidePastore** [comment]
Hi @antonioturdo. Yes, I'm interested in this. 👍

**Comment by antonioturdo** [comment]
#12
