### ISSUE TITLE
Traduzione in italiano

### ISSUE THREAD

**Issue by AndrewDevIT** [DavidePastore/codice-fiscale#27]
Perchè non tradurre questa repo in italiano, non credo degli inglesi vengano a vedere come calcolare un codice fiscale o.o

**Comment by DavidePastore** [comment]
Ciao @AndrewDevIT. Sicuramente tanti utenti italiani finiscono su questa repo ma penso che ce ne siano anche alcuni che non conoscono la nostra lingua. Penso che la migliore cosa da fare sia creare un README-it.md alternativo per avere la documentazione tradotta in italiano. Son ben accette delle pull request in tal senso.

**Comment by loviuz** [comment]
Appena fatta la pull request :-)
Noi lo usiamo nel nostro gestionale, per cui ho approfittato per contribuire in qualche modo...

**Comment by DavidePastore** [comment]
Closed by #30.
