### ISSUE TITLE
Problems with accented chars

### ISSUE THREAD

**Issue by angelods** [DavidePastore/codice-fiscale#28]
Hello Davide,
using your repo I noticed that it does not handle correctly the cases of names/surnames with accented chars. To be clear, the following test data will make the `CalculatorTest.php` fail:
```
array(
  new Subject(
    array(
      'name' => "Annalisa",
      'surname' => "Lisà",
      'birthDate' => '1980-04-04',
      'gender' => 'F',
      'belfioreCode' => 'H501',
    )
  ),
  -1,
  'LSINLS80D44H501F',
),
```
Here's the result:
```
1) CodiceFiscale\CalculatorTest::testCalculate with data set #17 (CodiceFiscale\Subject, -1, 'LSINLS80D44H501F')
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'LSINLS80D44H501F'
+'LS�NLS80D44H501M'
```
Given I already fixed this behavior in my code, I would be glad to submit a PR.

Thank you,
Angelo

**Comment by DavidePastore** [comment]
Hi @angelods , thanks for raising issue. If you have a fix ready for this, submit a PR and I would be more than happy to accept it.

**Comment by angelods** [comment]
https://github.com/DavidePastore/codice-fiscale/pull/29

**Comment by DavidePastore** [comment]
Closed with #29.

**Comment by DavidePastore** [comment]
@angelods  You can find this in the last release (0.4.1).

**Comment by angelods** [comment]
thank you @DavidePastore
