### ISSUE TITLE
PHP 7.4 compatibility

### ISSUE THREAD

**Issue by Dasc3er** [DavidePastore/codice-fiscale#35]
There seems to be a compatibility problem with PHP 7.4: "Array and string offset access syntax with curly braces is deprecated" in `src\CodiceFiscale\Validator.php:283`.

**Comment by nevnein** [comment]
As it is a deprecation notice more than an error, a quick workaround is to suppress such warnings:
`error_reporting(E_ALL ^ E_DEPRECATED);`
I've removed them and the everything looks fine on 7.4.2.

**Comment by silvioimp78** [comment]
Ho lo stesso problema con la libreria. 
In realtà il fix sarebbe pure veloce da fare. Potresti dirmi entro quanto tempo rilascerai la l'aggiornamento alla libreria. 

Grazie.

**Comment by DavidePastore** [comment]
Thanks for reporting this. Fixed in version 0.6.0!
