### ISSUE TITLE
Use a proper PSR-4 namespace

### ISSUE THREAD

**Issue by alxy** [DavidePastore/codice-fiscale#42]
Hi,

can you adjust your `composer.json` and file structure to use a proper PSR-4 compliant namesapcing scheme? [See here](https://stackoverflow.com/a/36167886/1907837) why you should do it.

I suggest mapping `\\DavidePastore\\CodiceFiscale` to `src/`

**Comment by DavidePastore** [comment]
Hi @alxy. Thanks for opening this issue. Feel free to create a PR if you already know the steps required to do it.

**Comment by DavidePastore** [comment]
@alxy I created the #43 PR to face this issue. What do you think about it? I preferred to use the same namespace as before (`CodiceFiscale\\`) instead of using `DavidePastore\\CodiceFiscale\\`

**Comment by alxy** [comment]
Looks good to me! :)

**Comment by DavidePastore** [comment]
Closed by #43.
