### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by kokoko3k** [DavidePastore/codice-fiscale#55]
Hi there,
I'm unable to find a license for your work.
Without it, no one is allowed to use your code, am i blind or "codice-fiscale"  is missing one?

Thanks!

**Comment by DavidePastore** [comment]
Hi @kokoko3k , you're right, the license is missing. I'm going to include it.

**Comment by DavidePastore** [comment]
Hi @kokoko3k. I added the license 😄

**Comment by kokoko3k** [comment]
Thank you very much!

Il giorno dom 16 mag 2021 alle ore 20:25 Davide Pastore <
***@***.***> ha scritto:
