### ISSUE TITLE
PHP 7.4 not supported

### ISSUE THREAD

**Issue by bellu** [DavidePastore/codice-fiscale#62]
I've tried to use this package but it seems that is not working on PHP versions >= 7.4.

Compile Error: Array and string offset access syntax with curly braces is no longer supported
in vendor/davidepastore/codice-fiscale/src/CodiceFiscale/Validator.php (line 283)

**Comment by DavidePastore** [comment]
Hi @bellu. Which library version are you using?

**Comment by DavidePastore** [comment]
Hi @bellu. Are you still facing that issue?

**Comment by bellu** [comment]
i was using an old version, you can close the issue. 
I didn't notice this, sorry.

**Comment by DavidePastore** [comment]
Thanks for confirming 😄
