### ISSUE TITLE
Curly braces is no longer supported

### ISSUE THREAD

**Issue by augustofagioli** [DavidePastore/codice-fiscale#65]
PHP 8.1.13  gives error below:

`PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in .../vendor/davidepastore/codice-fiscale/src/CodiceFiscale/Validator.php on line 292, 
`

**Comment by DavidePastore** [comment]
Hi @augustofagioli. Which version of the library are you using?

**Comment by augustofagioli** [comment]
your question makes sense. We were on 0.5.0
Latest 0.9.0 works superfine!
Thanks
Closing
