### ISSUE TITLE
Can't use method return value in write context

### ISSUE THREAD

**Issue by augustofagioli** [DavidePastore/codice-fiscale#66]
PHP 8.1.13 gives error below:

`PHP Fatal error:  Can't use method return value in write context in .../davidepastore/codice-fiscale/src/CodiceFiscale/Validator.php on line 292,
`

`$this->codiceFiscaleWithoutOmocodia($characterIndex) = $newChar;`

**Comment by DavidePastore** [comment]
Hi @augustofagioli. Which version of the `codice-fiscale` library are you using?

**Comment by augustofagioli** [comment]
your question makes sense. We were on 0.5.0
Latest 0.9.0 works superfine!
Thanks
Closing
