### ISSUE TITLE
Please, release a version compatibile with PHP 8.1 and 8.2

### ISSUE THREAD

**Issue by realtebo** [DavidePastore/codice-fiscale#70]
As for title, please, release a version compatibile with PHP 8.1 and 8.2

We are upgrading a project using your excellent package. 

But its composer it stopped at 8.0

**Comment by DavidePastore** [comment]
Hi @realtebo. Which version of the `codice-fiscale` are you using?

**Comment by LorenzoAlu** [comment]
Buondi @DavidePastore.

L'errore a cui si riferisce @realtebo e' il seguente su php 8.1 e oltre.

```
In AbstractCalculator.php line 150:
                                                                                  
  Array and string offset access syntax with curly braces is no longer supported  
                                                                                
```

Penso basti aggiornare quel pezzetto di codice :)

Se non hai tempo dimmi pure che apro io un PR.

saluti

**Comment by DavidePastore** [comment]
Ciao @LorenzoAlu. Grazie per il tuo messaggio. Quale versione del pacchetto stai utilizzando?

**Comment by LorenzoAlu** [comment]
Perdona @DavidePastore , ho aggiornato il pacchetto all'ultima versione e non ho piu' quell'errore.
:D

**Comment by DavidePastore** [comment]
Perfetto, @LorenzoAlu.
@realtebo, is this problem solved for you after you update the package to the latest version as well?

**Comment by realtebo** [comment]
@DavidePastore , mi spiace ma nel frattempo il progetto non ha più migrato,  ma sono certo che la soluzione sia corretta

**Comment by DavidePastore** [comment]
Grazie per la conferma, @realtebo. Chiudo la issue.
