### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Cannot assign an empty string to a string offset in ..../vendor/davidepastore/codice-fiscale/src/Calculator.php:242

### ISSUE THREAD

**Issue by hormander** [DavidePastore/codice-fiscale#74]
Sometime happen the following issue:

PHP Fatal error:  Uncaught Error: Cannot assign an empty string to a string offset in .../vendor/davidepastore/codice-fiscale/src/Calculator.php:242

It seem happen with PHP 8.3

**Comment by DavidePastore** [comment]
Hi @hormander. Could you please tell me how you are using the library and which parameters are you passing to the `Calculator` constructor?

**Comment by hormander** [comment]
Hi Davide,

I further looked into, and I found the issue is generated from a wrong belfiore code (it had just 2 character)
If you want to reproduce the issue you have to put a wrong belfiore code (I used the following: XK)

Thanks in advance,
m
