### ISSUE TITLE
[HELP] Latest version install issue

### ISSUE THREAD

**Issue by MarcoRavich** [DavidePastore/codice-fiscale#75]
Ciao Davide,
just tried to install using `composer require davidepastore/codice-fiscale` but it aims:

> Cannot use davidepastore/codice-fiscale's latest version v0.9.1 as it requires ext-intl * which is missing from your platform.
>

And installed old 0.5.0

How to solve ? Thanks in advance !

nota: sono - e parlo - italiano eh ;)

**Comment by DavidePastore** [comment]
Ciao @MarcoRavich,

please, ensure that you installed and enabled the [intl extension](https://www.php.net/manual/en/book.intl.php). Maybe [this link](https://stackoverflow.com/questions/33869521/how-can-i-enable-php-extension-intl) could be useful as well.

**Comment by MarcoRavich** [comment]
Worked, thanks !
